---
- hosts: serveurweb1
  tasks:
  - name: Installation paquets
    apt:
      name: nginx
      state: present

  - name: supression du vhost par default de nginx
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent
    notify: restart nginx

  - name: copie de la conf nginx
    copy:
      src: ./cdl2017.conf
      dest: /etc/nginx/sites-available/
    notify: restart nginx

  - name: active le site CDL 2017
    command: ln -s /etc/nginx/sites-available/cdl2017.conf /etc/nginx/sites-enabled/cdl2017.conf
    # idempotence !
    args:
      creates: /etc/nginx/sites-enabled/cdl2017.conf
    notify: restart nginx

  - name: copie fichier index
    copy:
      src: ./index.html
      dest: /var/www/html/

  - name: copie fichier d'erreur 404
    copy:
      src: ./user_not_found.html
      dest: /var/www/html/

# Creation d'un utilisateur avec page par défaut
  - name: création de l'utilisateur cdl2017
    user:
      name: cdl2017

  - name: création du dossier public sur l'utilisateur
    file:
      path: /home/cdl2017/public
      state: directory

  - name: copie fichier index utilisateur
    copy:
      src: ./my_index.html
      dest: /home/cdl2017/public/

  handlers:
    - name: restart nginx
      systemd:
        name: nginx
        state: restarted
